M_ZERO_1 = "➥ 𝙼𝚎𝚗𝚞 ❖ - 𝙿𝚊𝚐𝚎 𝟷"
M_ZERO_2 = "<b>1 ➽ 15 Bishoujo Hyouryuuki\n\n2 ➽ 25-sai no Joshikousei\n\n3 ➽ 3-byougo, Yajuu</b>"
M_ZERO_3 = "<b>1 ➽ 300 Yen no Otsukiai\n\n2 ➽ 3Piece The Animation\n\n3 ➽ 3Ping Lovers!</b>"


M_A_1 = "➥ 𝙼𝚎𝚗𝚞 𝙰 - 𝙿𝚊𝚐𝚎 𝟷"
M_A_2 = "<b>1 ➽ A Size Classmate\n\n2 ➽ Abandon: 100 Nuki Shinai to Derarenai Fushigi na Kyoushitsu\n\n3 ➽ Aibeya The Animation</b>"
M_A_3 = "<b>1 ➽ Aikagi The Animation\n\n2 ➽ Aisai Nikki\n\n3 ➽ Aisei Tenshi Love Mary: Akusei Jutai</b>"
M_A_4 = "<b>1 ➽ Ajisai no Chiru Koro ni\n\n2 ➽ Akane wa Tsumare Somerareru\n\n3 ➽ Akebi no Hana: Maho</b>"
M_A_5 = "<b>1 ➽ Akibakei Kanojo\n\n2 ➽ Akina to Onsen de H Shiyo!\n\n3 ➽ Aku no Onna Kanbu</b>"
M_A_6 = "<b>1 ➽ Aku no Onna Kanbu: Full Moon Night\n\n2 ➽ Aku no Onna Kanbu: Full Moon Night R\n\n3 ➽ Alignment You! You!</b>"
M_A_7 = "<b>1 ➽ Allargando The Animation\n\n2 ➽ Amai Choubatsu: Watashi wa Kanshu Senyou Pet\n\n3 ➽ Amakano</b>"
M_A_8 = "<b>1 ➽ Amanee!: Tomodachinchi de Konna Koto ni Naru Nante! \n\n2 ➽ Ana no Oku no Ii Tokoro\n\n3 ➽ Anata Dake Konbanwa</b>"
M_A_9 = "<b>1 ➽ Anata wa Watashi no Mono\n\n2 ➽ Ane Chijo: Max Heart\n\n3 ➽ Ane Haramix</b>"
M_A_10 = "<b>1 ➽ Ane Koi: Suki Kirai Daisuki\n\n2 ➽ Ane Kyun!: Joshi ga Ie ni Kita!\n\n3 ➽ Ane to Boin</b>"
M_A_11 = "➥ 𝙼𝚎𝚗𝚞 𝙰 - 𝙿𝚊𝚐𝚎 𝟸"
M_A_12 = "<b>1 ➽ Ane Yome Quartet\n\n2 ➽ Anehame: Ore no Hatsukoi ga Jisshi na Wake ga Nai\n\n3 ➽ Aneimo</b>"
M_A_13 = "<b>1 ➽ Anejiru The Animation: Shirakawa Sanshimai ni Omakase\n\n2 ➽ Anejiru 2 The Animation: Shirakawa Sanshimai ni Omakase\n\n3 ➽ Aneki no Kounai Kaikinbi</b>"
M_A_14 = "<b>1 ➽ Anette-san to Liliana-san The Animation\n\n2 ➽ Aniki no Yome-san nara, Ore ni Hamerarete Hiihii Itteru Tokoro Da yo\n\n3 ➽ Aniyome wa Ijippari</b>"
M_A_15 = "<b>1 ➽ Ano Danchi no Tsuma-tachi wa… The Animation\n\n2 ➽ Ano Ko no Kawari ni Suki na Dake\n\n3 ➽ Anoko to Iikoto</b>"
M_A_16 = "<b>1 ➽ Araiya-san!: Ore to Aitsu ga Onnayu de!?\n\n2 ➽ Ayatsuri Haramase Dream Note</b>"


M_B_1 = "➥ 𝙼𝚎𝚗𝚞 𝙱 - 𝙿𝚊𝚐𝚎 𝟷"
M_B_2 = "<b>1 ➽ BaBuKa: Gokudou no Tsuma\n\n2 ➽ Baka Dakedo Chinchin Shaburu no Dake wa Jouzu na Chii-chan\n\n3 ➽ Baka na Imouto wo Rikou ni Suru no wa Ore no XX Dake na Ken ni Tsuite</b>"
M_B_3 = "<b>1 ➽ Baku Ane: Otouto Shibocchau zo! The Animation\n\n2 ➽ Baku Ane 2: Otouto Ippai Shibocchau zo! The Animation\n\n3 ➽ Betsu ni Anta no Tame ni Ookiku Nattan Janain Dakara ne!!</b>"
M_B_4 = "<b>1 ➽ Bi-chiku Beach: Nangoku Nyuujoku Satsueikai\n\n2 ➽ Bible Black\n\n3 ➽ Bible Black Gaiden</b>"
M_B_5 = "<b>1 ➽ Bible Black Only Version\n\n2 ➽ Bible Black: New Testament\n\n3 ➽ Bijukubo</b>"
M_B_6 = "<b>1 ➽ Bikyaku Seido Kaichou Ai\n\n2 ➽ Binkan Athlete\n\n3 ➽ Bitch Gakuen ga Seijun na Hazu ga Nai!!?</b>"
M_B_7 = "<b>1 ➽ Bitch na Inane-sama\n\n2 ➽ Black Gate: Kanin no Gakuen\n\n3 ➽ Bloods Inraku No Ketsuzoku 2</b>"
M_B_8 = "<b>1 ➽ Boku Dake no Hentai Kanojo The Animation\n\n2 ➽ Boku ni Sexfriend ga Dekita Riyuu\n\n3 ➽ Boku no Pico</b>"
M_B_9 = "<b>1 ➽ Boku no Yayoi-san\n\n2 ➽ Boku no Yayoi-san 2\n\n3 ➽ Boku to Joi no Shinsatsu Nisshi</b>"
M_B_10 = "<b>1 ➽ Boku to Misaki-sensei\n\n2 ➽ Boku to Nurse no Kenshuu Nisshi\n\n3 ➽ Boku to Sensei to Tomodachi no Mama</b>"
M_B_11 = "➥ 𝙼𝚎𝚗𝚞 𝙱 - 𝙿𝚊𝚐𝚎 𝟸"
M_B_12 = "<b>1 ➽ Brandish\n\n2 ➽ Busou Shoujotai: Blade Briders The Animation\n\n3 ➽ Bust to Bust: Chichi wa Chichi ni</b>"
M_B_13 = "<b>1 ➽ Buta Himesama\n\n2 ➽ Buta no Gotoki Sanzoku ni Torawarete Shojo wo Ubawareru Kyonyuu Himekishi & Onna Senshi</b>"


M_C_1 = "➥ 𝙼𝚎𝚗𝚞 𝙲 - 𝙿𝚊𝚐𝚎 𝟷"
M_C_2 = "<b>1 ➽ Cafe Junkie\n\n2 ➽ Cambrian\n\n3 ➽ Cartagra: Tsuki Gurui no Yamai</b>"
M_C_3 = "<b>1 ➽ Cele Kano\n\n2 ➽ Cherry & Gal’s\n\n3 ➽ Chicchana Onaka</b>"
M_C_4 = "<b>1 ➽ Chichiiro Toiki\n\n2 ➽ Chii-chan Kaihatsu Nikki\n\n3 ➽ Chiisana Tsubomi no Sono Oku ni…</b>"
M_C_5 = "<b>1 ➽ Chijoku no Seifuku\n\n2 ➽ Chijoku Shinsatsushitsu (Doctor Shameless)\n\n3 ➽ Chikan Juunin-tai The Animation</b>"
M_C_6 = "<b>1 ➽ Chikan no Licence\n\n2 ➽ Chikan Shita Joshikousei to Sonogo, Musaboriau you na Doero Junai\n\n3 ➽ Chinetsu Karte: The Devilish Cherry</b>"
M_C_7 = "<b>1 ➽ Chizuru-chan Kaihatsu Nikki\n\n2 ➽ Choukou Sennin Haruka\n\n3 ➽ Choukou Tenshi Escalayer</b>"
M_C_8 = "<b>1 ➽ Chu Shite Agechau: Oshikake Oneesan no Seikou Chiryou\n\n2 ➽ Classmate no Okaasan\n\n3 ➽ Cleavage</b>"
M_C_9 = "<b>1 ➽ Colosseum no Senki: Another Story\n\n2 ➽ Cosplay Change: Pure-kei Joshidaisei no Kiken na Seiheki\n\n3 ➽ Cosplay Rakuen</b>"
M_C_10 = "<b>1 ➽ Cosplay Roshutsu Kenkyuukai\n\n2 ➽ Creamy Pie\n\n3 ➽ Crimson Girls: Chikan Shihai</b>"

M_D_1 = "➥ 𝙼𝚎𝚗𝚞 𝙳 - 𝙿𝚊𝚐𝚎 𝟷"
M_D_2 = "<b>1 ➽ D-Spray\n\n2 ➽ Daiakuji: The Xena Buster\n\n3 ➽ Dainiji Ura Nyuugakushiken The Animation</b>"
M_D_3 = "<b>1 ➽ Daisuki na Haha\n\n2 ➽ Daraku Reijou The Animation\n\n3 ➽ Dark Blue</b>"
M_D_4 = "<b>1 ➽ Dekakute Ecchi na Ore no Ane\n\n2 ➽ Delivery Chinko o Tanomitai Onee-san\n\n3 ➽ Demon Busters: Ecchi na Ecchi na Demon Taiji</b>"
M_D_5 = "<b>1 ➽ Demonion: Gaiden\n\n2 ➽ Diabolus: Kikoku\n\n3 ➽ Discipline</b>"
M_D_6 = "<b>1 ➽ Discipline Zero\n\n2 ➽ Do S na Seitokaichou-sama ga M Note ni Shihai Saremashita\n\n3 ➽ Dokidoki Little Ooyasan</b>"
M_D_7 = "<b>1 ➽ DokiDoki Oyako Lesson: Oshiete H na Obenkyou\n\n2 ➽ Donburi Kazoku [Like Mother Like Daughter]\n\n3 ➽ Dorei Maid Princess</b>"
M_D_8 = "<b>1 ➽ Dorei Usagi to Anthony The Animation\n\n2 ➽ Doukyuusei Remake The Animation\n\n3 ➽ Dropout</b>"


M_E_1 = "➥ 𝙼𝚎𝚗𝚞 𝙴 - 𝙿𝚊𝚐𝚎 𝟷"
M_E_2 = "<b>1 ➽ Ecchi na Onee-chan ni Shiboraretai\n\n2 ➽ Ecchi na Shintai Sokutei Anime Edition\n\n3 ➽ Eisai Kyoiku</b>"
M_E_3 = "<b>1 ➽ Elf Hime Nina\n\n2 ➽ Elf no Futagohime: Willan to Arsura\n\n3 ➽ Elf no Oshiego to Sensei</b>"
M_E_4 = "<b>1 ➽ Enbi\n\n2 ➽ Enbo (Taboo Charming Mother)\n\n3 ➽ Energy Kyouka!</b>"
M_E_5 = "<b>1 ➽ Enjo Kouhai\n\n2 ➽ Enkou JK Bitch Gal: Ojisan to Namapako Seikatsu\n\n3 ➽ Enkou Shoujo: Rikujoubu Yukki no Baai The Animation</b>"
M_E_6 = "<b>1 ➽ Enyoku\n\n2 ➽ Ero Ishi: Seijun Bishoujo wo Kotoba Takumi ni Hametai Houdai\n\n3 ➽ Ero Konbini Tenchou</b>"
M_E_7 = "<b>1 ➽ Ero Manga! H mo Manga mo Step-up♪ \n\n2 ➽ Ero Zemi: Ecchi ni Yaruki ni ABC\n\n3 ➽ Eroge de Subete wa Kaiketsu Dekiru! The Animation</b>"
M_E_8 = "<b>1 ➽ Eroge H mo Game mo Kaihatsu Zanmai\n\n2 ➽ Eromame\n\n3 ➽ Eroriman</b>"
M_E_9 = "<b>1 ➽ Eroriman 2\n\n2 ➽ Eternity: Shinya no Nurekoi Channel\n\n3 ➽ Etsuraku no Tane The Animation</b>"
M_E_10 = "<b>1 ➽ Euphoria</b>"


M_F_1 = "➥ 𝙼𝚎𝚗𝚞 𝙵 - 𝙿𝚊𝚐𝚎 𝟷"
M_F_2 = "<b>1 ➽ Fault!!\n\n2 ➽ Fault!! Service: Aratanaru Rival\n\n3 ➽ Fechikano!</b>"
M_F_3 = "<b>1 ➽ Fella Hame Lips\n\n2 ➽ Fella Pure: Mitarashi-san Chi no Jijou The Animation\n\n3 ➽ Fighting of Ecstasy</b>"
M_F_4 = "<b>1 ➽ First Love\n\n2 ➽ Floating Material\n\n3 ➽ Front Innocent: Mou Hitotsu no Lady Innocent</b>"
M_F_5 = "<b>1 ➽ Fukai ni Nemuru Oujo no Abaddon\n\n2 ➽ Fukubiki! Triangle: Futaba wa Atafuta\n\n3 ➽ Fukubiki! Triangle: Miharu After</b>"
M_F_6 = "<b>1 ➽ Furifure The Animation\n\n2 ➽ Furifure 2\n\n3 ➽ Furueru Kuchibiru</b>"
M_F_7 = "<b>1 ➽ Furyou ni Hamerarete Jusei Suru Kyonyuu Okaasan The Animation\n\n2 ➽ Futabu!\n\n3 ➽ Futabu!! 2</b>"
M_F_8 = "<b>1 ➽ Futabu! Mix: Futanari World\n\n2 ➽ Futago no Haha Seihonnou\n\n3 ➽ Fuurinkanzan</b>"
